name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_lint:
    runs-on: ubuntu-latest
    if: ${{ !github.event.created }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm ci
    - name: Making sure 'npm run lint' and 'npm run format' does not changes anything.
      run: |
        npm run lint:check
        npm run format:check
        
  test_node:
    runs-on: ubuntu-latest
    needs: test_lint
    strategy:
      matrix:
        node: [ '14', '13', '12', '11', '10', '8' ]
    name: Test with Node v${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build
    - run: npm run test
